CREATE TABLE USUARIO(
	ID			UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	EMAIL			NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(50)		NOT NULL,
	PRIMARY KEY(ID))
GO

CREATE TABLE CATEGORIA(
	ID			UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID))
	                                                                                     
GO

CREATE TABLE FILME(
	ID			UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	DATA			DATE			NOT NULL,
	TIPO			INTEGER			NOT NULL,
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	IDCATEGORIA		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(ID),
	FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(ID))
GO